services:
  mysql:
    image: mysql:8.0
    container_name: gestionretours-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 90443605
      MYSQL_DATABASE: gestion_retours
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: gestionretours-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

  frontend:
    build:
      context: "C:/Users/GIGABYTE/Desktop/2GL-A/semestre2/Spring Boot/gestion-retours-frontend"
    container_name: gestionretours-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  mysql_data: